version: '3.8'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-server
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./doc:/home/node/doc
      - ./project:/home/node/project
      - ./output_pages:/home/node/output_pages
#    deploy:
 #     resources:
  #      limits:
   #       cpus: '2.0'   # จำกัด CPU 2 cores
    #      memory: 4G    # จำกัด RAM 4GB
